from __future__ import annotations

from typing import Protocol

from services.github_provider.models import ManagedDestination, ManagedRepository, ProviderOperation, ProviderReceipt


class GitHubProviderRepository(Protocol):
    def get_destination(self, destination_id: str) -> ManagedDestination | None: ...
    def get_hape_destination(self) -> ManagedDestination | None: ...
    def find_destination_by_installation(self, installation_id: int) -> ManagedDestination | None: ...
    def find_customer_destination(self, tenant_subject: str, installation_id: int) -> ManagedDestination | None: ...
    def upsert_destination(self, destination: ManagedDestination) -> None: ...
    def get_repository(self, repository_id: str) -> ManagedRepository | None: ...
    def find_repository_by_name(self, repository_name: str) -> ManagedRepository | None: ...
    def upsert_repository(self, repository: ManagedRepository) -> None: ...
    def get_operation(self, operation_id: str) -> ProviderOperation | None: ...
    def find_operation(self, tenant_subject: str, operation: str, idempotency_key: str) -> ProviderOperation | None: ...
    def upsert_operation(self, operation: ProviderOperation) -> None: ...
    def grant_consumed(self, jti: str) -> bool: ...
    def consume_grant(self, jti: str, issuer: str, grant_sub: str, operation: str, input_digest: str, expires_at: str, consumed_at: str) -> None: ...
    def append_receipt(self, receipt: ProviderReceipt) -> None: ...
    def get_receipt(self, receipt_id: str) -> ProviderReceipt | None: ...
    def get_latest_receipt(self, operation_id: str) -> ProviderReceipt | None: ...
    def put_setup_state(self, state: str, tenant_subject: str, code_challenge: str, expires_at: str) -> None: ...
    def consume_setup_state(self, state: str, tenant_subject: str, now: str) -> str | None: ...
    def reserve_name(self, repository_name: str) -> bool: ...
    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


if __name__ == "__main__":
    print(GitHubProviderRepository)
