apiVersion: v1
kind: Service
metadata:
  name: hape-dora-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: hape-dora-exporter
spec:
  selector:
    app.kubernetes.io/name: hape-dora-exporter
  ports:
  - name: metrics
    port: 9120
    targetPort: metrics
