FROM python:3.12-bookworm

RUN apt update && apt install -y awscli && pip install --upgrade hape

WORKDIR /workspace

COPY . /workspace

WORKDIR /workspace/playground

ENTRYPOINT ["sleep", "infinity"]
